blogs/urls.py
from django.urls import path
from . import views

app_name="blogs"

urlpatterns = [
    path('', views.blogs, name='blog_list'),
    path('category/<slug:category_slug>/', views.blogs, name='blog_list_category'),
    path('tag/<slug:tag_slug>/', views.blogs, name='blog_list_tag'),
    path('detail/<slug:blog_slug>/', views.blog_detail, name='blog_detail')
]

my_restart/urls.py
from django.contrib import admin
from django.urls import include,path
from users.views import *
from django.conf import settings 
from django.conf.urls.static import static 


urlpatterns = [
    path('', Home, name='home'),
    path('about/', about, name="about"),
    path('faq/', faq, name="faq"),
    path('contact/', contact, name="contact"),

    path('add_to_cart/<int:product_id>/', add_to_cart, name='add_to_cart'),
    path('cart/', view_cart, name='view_cart'),
    path('update_cart_item/<int:item_id>/<int:new_quantity>/', update_cart_item, name='update_cart_item'),
    path('remove_from_cart/<int:cart_item_id>/', remove_from_cart, name='remove_from_cart'),
    path('checkout/', checkout, name='checkout'),
    path('address/', view_address, name='view_address'),
    path('add-address/', add_address, name='add_address'),
    path('pay/', payment, name='payment'),
    path('checkout-session/', create_checkout_session, name='api_checkout_session'),
    path('payment-details', payment_details, name="view_payment_details"),
    path('orders/', orders_list, name="view_my_orders"),
    path('order-details/<str:order>', order_details, name="view_order_details"),


    
    
    path('account/', Signup),
    path('logout/', user_logout),
    path('users/', include('users.urls')),


    path('blogs/', include('blogs.urls')),
    path('products/', include('products.urls')),
    path('admin/', admin.site.urls),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from . import views

app_name="products"

urlpatterns = [
    # path('', views.products, name='product_list'),
    path('detail/<slug:product_slug>/', views.product_detail, name='product_detail'),
    # for auto load on scroll
    path('all/', views.products1, name='product_list1'),
    path('all/load-more-products/', views.load_more_products, name='load_more_products'),

    

    path('<slug:category_slug>/', views.products, name='product_list_category'),
    path('<slug:category_slug>/<slug:sub_category_slug>/', views.products, name='product_list_subcategory'),
]

users/urls.py
from django.urls import path
from . import views

app_name="users"

urlpatterns = [
    path('', views.users, name='users'),
    path('signup', views.Signup, name='Signup'),
    path('signin', views.Signin, name='Signin'),
    path('logout', views.user_logout, name='logout'),
    
    # path('', views.Home, name='home'),
]

templates/home/about.html
{% extends "includes/base.html" %}
{% load static %}


{% block specific_css %}
<link href="{% static 'css/about.css' %}" rel="stylesheet">
{% endblock %}

{% block main_content %}
	<main class="bg_gray">
			<div class="container margin_60_35 add_bottom_30">
				<div class="main_title">
					<h2>About Ecom</h2>
					<p>this is a test line.</p>
				</div>
				<div class="row justify-content-center align-items-center">
					<div class="col-lg-5">
						<div class="box_about">
							<h2>Top Products</h2>
							<p class="lead">Est falli invenire interpretaris id, magna libris sensibus mel id.</p>
							<p>Per eu nostrud feugiat. Et quo molestiae persecuti neglegentur. At zril definitionem mei, vel ei choro volumus. An tota nulla soluta has, ei nec essent audiam, te nisl dignissim vel. Ex velit audire perfecto pro, ei mei doming vivendo legendos. Cu sit magna zril, an odio delectus constituto vis. Vis ludus omnesque ne, est veri quaeque ad.</p>
							<img src="{% static 'img/arrow_about.png' %}" alt="" class="arrow_1">
						</div>
					</div>
					<div class="col-lg-5 pl-lg-5 text-center d-none d-lg-block">
							<img src="{% static 'img/about_1.svg' %}" alt="" class="img-fluid" width="350" height="268">
					</div>
				</div>
				<!-- /row -->
				<div class="row justify-content-center align-items-center">
					<div class="col-lg-5 pr-lg-5 text-center d-none d-lg-block">
							<img src="{% static 'img/about_2.svg' %}" alt="" class="img-fluid" width="350" height="268">
					</div>
					<div class="col-lg-5">
						<div class="box_about">
							<h2>Top Brands</h2>
							<p class="lead">Est falli invenire interpretaris id, magna libris sensibus mel id.</p>
							<p>Per eu nostrud feugiat. Et quo molestiae persecuti neglegentur. At zril definitionem mei, vel ei choro volumus. An tota nulla soluta has, ei nec essent audiam, te nisl dignissim vel. Ex velit audire perfecto pro, ei mei doming vivendo legendos. Cu sit magna zril, an odio delectus constituto vis. Vis ludus omnesque ne, est veri quaeque ad.</p>
							<img src="{% static 'img/arrow_about.png' %}" alt="" class="arrow_2">
						</div>
					</div>
				</div>
				<!-- /row -->
				<div class="row justify-content-center align-items-center ">
					<div class="col-lg-5">
						<div class="box_about">
							<h2>+5000 products</h2>
							<p class="lead">Est falli invenire interpretaris id, magna libris sensibus mel id.</p>
							<p>Per eu nostrud feugiat. Et quo molestiae persecuti neglegentur. At zril definitionem mei, vel ei choro volumus. An tota nulla soluta has, ei nec essent audiam, te nisl dignissim vel. Ex velit audire perfecto pro, ei mei doming vivendo legendos. Cu sit magna zril, an odio delectus constituto vis. Vis ludus omnesque ne, est veri quaeque ad.</p>
						</div>

					</div>
					<div class="col-lg-5 pl-lg-5 text-center d-none d-lg-block">
							<img src="{% static 'img/about_3.svg' %}" alt="" class="img-fluid" width="350" height="316">
					</div>
				</div>
				<!-- /row -->
			</div>
			<!-- /container -->
		
			<div class="bg_white">
				<div class="container margin_60_35">
					<div class="main_title">
						<h2>Why Choose Allaia</h2>
						<p>Cum doctus civibus efficiantur in imperdiet deterruisset.</p>
					</div>
					<div class="row">
						<div class="col-lg-4 col-md-6">
							<div class="box_feat">
								<i class="ti-medall-alt"></i>
								<h3>+ 1000 Customers</h3>
								<p>Id mea congue dictas, nec et summo mazim impedit. Vim te audiam impetus interpretaris, cum no alii option, cu sit mazim libris.</p>
							</div>
						</div>
						<div class="col-lg-4 col-md-6">
							<div class="box_feat">
								<i class="ti-help-alt"></i>
								<h3>H24 Support</h3>
								<p>Id mea congue dictas, nec et summo mazim impedit. Vim te audiam impetus interpretaris, cum no alii option, cu sit mazim libris. </p>
							</div>
						</div>
						<div class="col-lg-4 col-md-6">
							<div class="box_feat">
								<i class="ti-gift"></i>
								<h3>Great Sale Offers</h3>
								<p>Id mea congue dictas, nec et summo mazim impedit. Vim te audiam impetus interpretaris, cum no alii option, cu sit mazim libris.</p>
							</div>
						</div>
						<div class="col-lg-4 col-md-6">
							<div class="box_feat">
								<i class="ti-headphone-alt"></i>
								<h3>Help Direct Line</h3>
								<p>Id mea congue dictas, nec et summo mazim impedit. Vim te audiam impetus interpretaris, cum no alii option, cu sit mazim libris. </p>
							</div>
						</div>
						<div class="col-lg-4 col-md-6">
							<div class="box_feat">
								<i class="ti-wallet"></i>
								<h3>Secure Payments</h3>
								<p>Id mea congue dictas, nec et summo mazim impedit. Vim te audiam impetus interpretaris, cum no alii option, cu sit mazim libris.</p>
							</div>
						</div>
						<div class="col-lg-4 col-md-6">
							<div class="box_feat">
								<i class="ti-comments"></i>
								<h3>Support via Chat</h3>
								<p>Id mea congue dictas, nec et summo mazim impedit. Vim te audiam impetus interpretaris, cum no alii option, cu sit mazim libris. </p>
							</div>
						</div>
					</div>
					<!--/row-->
				</div>
			</div>
			<!-- /bg_white -->
		
		<div class="container margin_60">
			<div class="main_title">
				<h2>Meet Allaia Staff</h2>
				<p>Cum doctus civibus efficiantur in imperdiet deterruisset.</p>
			</div>
			<div class="owl-carousel owl-theme carousel_centered">
				<div class="item">
					<a href="#0">
						<div class="title">
							<h4>Julia Holmes<em>CEO</em></h4>
						</div><img src="{% static 'img/staff/1_carousel.jpg' %}" alt="">
					</a>
				</div>
				<div class="item">
					<a href="#0">
						<div class="title">
							<h4>Lucas Smith<em>Marketing</em></h4>
						</div><img src="{% static 'img/staff/2_carousel.jpg' %}" alt="">
					</a>
				</div>
				<div class="item">
					<a href="#0">
						<div class="title">
							<h4>Paul Stephens<em>Business strategist</em></h4>
						</div><img src="{% static 'img/staff/3_carousel.jpg' %}" alt="">
					</a>
				</div>
				<div class="item">
					<a href="#0">
						<div class="title">
							<h4>Pablo Himenez<em>Customer Service</em></h4>
						</div><img src="{% static 'img/staff/4_carousel.jpg' %}" alt="">
					</a>
				</div>
				<div class="item">
					<a href="#0">
						<div class="title">
							<h4>Andrew Stuttgart<em>Admissions</em></h4>
						</div><img src="{% static 'img/staff/5_carousel.jpg' %}" alt="">
					</a>
				</div>
			</div>
			<!-- /carousel -->
		</div>
		<!-- /container -->
	</main>
	<!--/main-->
{% endblock %}    	

templates/home/account.html
{% extends "includes/base.html" %}
{% load static %}



{% block specific_css %}
<link href="{% static 'css/account.css' %}" rel="stylesheet">
{% endblock %}

{% block main_content %}	
	<main class="bg_gray">
		
	<div class="container margin_30">
		<div class="page_header">
			<div class="breadcrumbs">
				<ul>
					<li><a href="#">Home</a></li>
					<li><a href="#">Category</a></li>
					<li>Page active</li>
				</ul>
		</div>
		<h1>Sign In or Create an Account</h1>
	</div>
	<!-- /page_header -->
			<div class="row justify-content-center">
			<div class="col-xl-6 col-lg-6 col-md-8">
				<div class="box_account">
					<form action="{% url 'users:Signin' %}" id="signin_form" method="POST">
						{% csrf_token %}
						<input type="hidden" name="next" value="{{ request.GET.next }}">
					<h3 class="client">Already Client</h3>
					<div class="form_container">
						<div class="row no-gutters">
							<div class="col-lg-6 pr-lg-1">
								<a href="#0" class="social_bt facebook">Login with Facebook</a>
							</div>
							<div class="col-lg-6 pl-lg-1">
								<a href="#0" class="social_bt google">Login with Google</a>
							</div>
						</div>
						<div class="divider"><span>Or</span></div>
						<div class="form-group">
							<input type="email" class="form-control" name="email" id="email" placeholder="Email*">
						</div>
						<div class="form-group">
							<input type="password" class="form-control" name="password_in" id="password_in" value="" placeholder="Password*">
						</div>
						<div class="clearfix add_bottom_15">
							<div class="checkboxes float-start">
								<label class="container_check">Remember me
									<input type="checkbox">
									<span class="checkmark"></span>
								</label>
							</div>
							<div class="float-end"><a id="forgot" href="javascript:void(0);">Lost Password?</a></div>
						</div>
						<div class="text-center"><input type="submit" value="Log In" class="btn_1 full-width"></div>
						<div id="forgot_pw">
							<div class="form-group">
								<input type="email" class="form-control" name="email_forgot" id="email_forgot" placeholder="Type your email">
							</div>
							<p>A new password will be sent shortly.</p>
							<div class="text-center"><input type="submit" value="Reset Password" class="btn_1"></div>
						</div>
					</div>
					</form>
					<!-- /form_container -->
				</div>
				<!-- /box_account -->
				<div class="row">
					<div class="col-md-6 d-none d-lg-block">
						<ul class="list_ok">
							<li>Find Locations</li>
							<li>Quality Location check</li>
							<li>Data Protection</li>
						</ul>
					</div>
					<div class="col-md-6 d-none d-lg-block">
						<ul class="list_ok">
							<li>Secure Payments</li>
							<li>H24 Support</li>
						</ul>
					</div>
				</div>
				<!-- /row -->
			</div>
			
		
			
			<div class="col-xl-6 col-lg-6 col-md-8">
				<div class="box_account">
					<form action="{% url 'users:Signup' %}" id="signup_form" method="POST">
					{% csrf_token %}
					<input type="hidden" name="next" value="{{ request.GET.next }}">
					<h3 class="new_client">New Client</h3> <small class="float-right pt-2">* Required Fields</small>
					<div class="form_container">
						<div class="form-group">
							<input type="email" class="form-control" name="email" id="email_2" placeholder="Email*">
						</div>
						<div class="form-group">
							<input type="password" class="form-control" name="password_in_2" id="password_in_2" value="" placeholder="Password*">
						</div>
						
						
						<div class="private box">
							<div class="row no-gutters">
								<div class="col-6 pr-1">
									<div class="form-group">
										<input type="text" name="fname" class="form-control" placeholder="Name*" >
									</div>
								</div>
								<div class="col-6 pl-1">
									<div class="form-group">
										<input type="text" name="lname" class="form-control" placeholder="Last Name*" >
									</div>
								</div>
								
							</div>
							
							
						</div>
						
						
						
						<div class="text-center"><input type="submit" value="Register" class="btn_1 full-width"></div>
					</div>
					<!-- /form_container -->
					</form>
				</div>
				<!-- /box_account -->
			</div>
		

		</div>
		<!-- /row -->
		</div>
		<!-- /container -->
	</main>
	<!--/main-->
{% endblock %}	
{% block specific_js %}

<script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.9/jquery.validate.js"></script>
<script type="text/javascript">
	$(document).ready(function(){
		$("#signup_form").validate({
		rules :{
			email : {
				required : true
			}
		},
		messages :{
			email : {
				required : 'Enter email'
			}
		}
		});
	});
</script>

{% endblock %}

templates/home/cart.html
{% extends "includes/base.html" %}
{% load static %}
{% block specific_css %}

<link href="{% static 'css/cart.css' %}" rel="stylesheet">

{% endblock %}

{% block main_content %}
	<main class="bg_gray">
		<div class="container margin_30">
			<div class="page_header">
				<div class="breadcrumbs">
					<ul>
						<li><a href="{% url 'home' %}">Home</a></li>
						<li>Cart</li>
					</ul>
				</div>
				<h1>Cart page</h1>
			</div>
			<!-- /page_header -->
			<table class="table table-striped cart-list">
				<thead>
					<tr>
						<th>
							Product
						</th>
						<th>
							Price
						</th>
						<th>
							Quantity
						</th>
						<th>
							Subtotal
						</th>
						<th>
							
						</th>
					</tr>
				</thead>
				<tbody>
					{% for item in cart_items %}
					<tr>
						<td>
							<div class="thumb_cart">
								{% for image in item.product.product_images.all|slice:":1" %}
								<img src="{{image.img.url}}" data-src="{{image.img.url}}"  class="lazy" alt="Image">
								{% endfor %}
							</div>
							<span class="item_cart">{{item.product}}</span>
						</td>
						<td>
							<strong>₹ {{item.product.price}}</strong>
						</td>
						<td>
							<div class="numbers-row" >
								<input type="text" value="{{item.quantity}}"  id="quantity_{{item.id}}" class="qty2" name="quantity_1" readonly>
								<div class="inc button_inc" onclick="update_cart_item('{{item.id}}')">+</div>
								<div class="dec button_inc" onclick="update_cart_item('{{item.id}}')">-</div>
							</div>
						</td>
						<td>
							<strong id="item_subtotal_{{item.id}}">₹  {% widthratio item.product.price 1 item.quantity  %}</strong>
						</td>
						<td class="options">
							<a href="{% url 'remove_from_cart' item.id %}"><i class="ti-trash"></i></a>
						</td>
					</tr>
					{% endfor %}
				</tbody>
			</table>

			<div class="row add_top_30 flex-sm-row-reverse cart_actions">
				<div class="col-sm-4 text-end">
					<!-- <button type="button" class="btn_1 gray">Update Cart</button> -->
				</div>
					<div class="col-sm-8">
					<div class="apply-coupon">
						<div class="form-group">
							<div class="row g-2">
								<div class="col-md-6"><input type="text" name="coupon-code" value="" placeholder="Promo code" class="form-control"></div>
								<div class="col-md-4"><button type="button" class="btn_1 outline">Apply Coupon</button></div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- /cart_actions -->
	
		</div>
		<!-- /container -->
		
		<div class="box_cart">
			<div class="container">
				<div class="row justify-content-end">
					<div class="col-xl-4 col-lg-4 col-md-6">
						<ul>
							
							<li id="final_amount">
								<span>Total</span> ₹ {{total_price}}
							</li>
						</ul>
						<a href="{% url 'checkout' %}" class="btn_1 full-width cart">Proceed to Checkout</a>
					</div>
				</div>
			</div>
		</div>
		<!-- /box_cart -->
		
	</main>
	<!--/main-->
{% endblock %}	


{% block specific_js %}


<script>
	function update_cart_item(cart_item_id){
		setTimeout(function(){
			new_quantity = $('#quantity_'+cart_item_id).val();
			var xhr = new XMLHttpRequest();
			xhr.open('POST', '/update_cart_item/' + cart_item_id + '/' + new_quantity + '/');
			var csrfToken = '{{ csrf_token }}';
			xhr.setRequestHeader('Content-Type', 'application/json');
			xhr.setRequestHeader('X-CSRFToken', csrfToken);
			xhr.onreadystatechange = function () {
				if (xhr.readyState === 4) {	
					if (xhr.status === 200) {
						var response = JSON.parse(xhr.responseText);
						if (response.success) {
							Swal.fire({ title: "", text: "Quantity updated successfully", icon: "success", });
							$("#item_subtotal_"+cart_item_id).html('₹ ' + response.new_subtotal);
							$("#final_amount").html('<span>Total</span> ₹ ' + response.total);
						} else {
							Swal.fire({ title: "", text: "Cart item not found", icon: "error", });
						}
					} else {
						Swal.fire({ title: "", text: "Error updating quantity", icon: "error", });
					}
				}
			};
			xhr.send();
		}, 1000);
	}
</script>
{% endblock %}	

templates/home/confirm.html
{% extends "includes/base.html" %}
{% load static %}

{% block specific_css %}
<link href="{% static 'css/checkout.css' %}" rel="stylesheet">
{% endblock %}


{% block main_content %}
	
	<main class="bg_gray">
		<div class="container">
            <div class="row justify-content-center">
				<div class="col-md-5">
					<div id="confirm">
						<div class="icon icon--order-success svg add_bottom_15">
							<svg xmlns="http://www.w3.org/2000/svg" width="72" height="72">
								<g fill="none" stroke="#8EC343" stroke-width="2">
									<circle cx="36" cy="36" r="35" style="stroke-dasharray:240px, 240px; stroke-dashoffset: 480px;"></circle>
									<path d="M17.417,37.778l9.93,9.909l25.444-25.393" style="stroke-dasharray:50px, 50px; stroke-dashoffset: 0px;"></path>
								</g>
							</svg>
						</div>
					<h2>Order completed!</h2>
					<p>You will receive a confirmation email soon!</p>
					</div>
				</div>
			</div>
			<!-- /row -->
		</div>
		<!-- /container -->
		
	</main>
	<!--/main-->

{% endblock %}

templates/home/index.html
{% extends "includes/base.html" %} 
{% load static %}
{% load custom_filters %}


{% block specific_css %}
<link href="{% static 'css/home_1.css' %}" rel="stylesheet">
{% endblock %}

{% block main_content %}
<main>
    <div id="carousel-home">
        <div class="owl-carousel owl-theme">

            {% for banner in banner_data %}


            <div class="owl-slide cover" style="background-image: url({{banner.imgg.url}});">
                <div class="opacity-mask d-flex align-items-center" data-opacity-mask="rgba(0, 0, 0, 0.5)">
                    <div class="container">
                        <div class="row justify-content-center justify-content-md-end">
                            <div class="col-lg-6 static">
                                <div class="slide-text text-end white">
                                    <h2 class="owl-slide-animated owl-slide-title">{{ banner.heading }}</h2>
                                    <p class="owl-slide-animated owl-slide-subtitle">
                                        {{ banner.description }}
                                    </p>
                                    {% if banner.product %}
                                        <div class="owl-slide-animated owl-slide-cta">
                                            <a class="btn_1" href="{% url 'products:product_detail' banner.product.slug  %}" role="button">Shop Now</a>
                                        </div>
                                    {% elif banner.sub_category %}
                                        <div class="owl-slide-animated owl-slide-cta">
                                            <a class="btn_1" href="{% url 'products:product_list_subcategory' banner.category.slug banner.sub_category.slug %}" role="button">Shop Now</a>
                                        </div>
                                    {% elif banner.category %}
                                        <div class="owl-slide-animated owl-slide-cta">
                                            <a class="btn_1" href="{% url 'products:product_list_category' banner.category.slug %}" role="button">Shop Now</a>
                                        </div>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!--/owl-slide-->

            {% endfor %}

            
        </div>
        <div id="icon_drag_mobile"></div>
    </div>
    
    
    <div class="container margin_60_35">
        <div class="main_title">
            <h2>New Listing</h2>
            <span>Products</span>
            <p>Top 8 Products</p>
        </div>
        <div class="row small-gutters">
            <!-- top products loop -->
            {% for product in product_list %}          
            

            <div class="col-6 col-md-4 col-xl-3">
                <div class="grid_item">
                    <figure>
                        <span class="ribbon off">  {% percent_discount product.price product.mrp %}   </span>                        
                        <a href="{% url 'products:product_detail' product.slug %}">
                            {% for image in product.product_images.all|slice:":2" %}
                                <img class="img-fluid lazy" src="{{image.img.url}}" data-src="{{image.img.url}}" alt="">
                            {% endfor %}
                        </a>
                    </figure>
                    <div class="rating"><i class="icon-star voted"></i><i class="icon-star voted"></i><i class="icon-star voted"></i><i class="icon-star voted"></i><i class="icon-star"></i></div>
                    <a href="{% url 'products:product_detail' product.slug %}">
                        <h3>{{ product.name }}</h3>

                        
                    </a>
                    <div class="price_box">
                        <span class="new_price">₹ {{ product.price }}</span>
                        <span class="old_price">₹ {{ product.mrp }}</span>
                    </div>
                    <ul>
                        <li><a href="#0" class="tooltip-1" data-bs-toggle="tooltip" data-bs-placement="left" title="Add to favorites"><i class="ti-heart"></i><span>Add to favorites</span></a></li>
                        
                        <li><a href="{% url 'add_to_cart' product.id %}" class="tooltip-1" data-bs-toggle="tooltip" data-bs-placement="left" title="Add to cart"><i class="ti-shopping-cart"></i><span>Add to cart</span></a></li>
                    </ul>
                </div>
                <!-- /grid_item -->
            </div>
            {% endfor %}
        </div>
        <!-- /row -->
    </div>
    <!-- /container -->

     

    <div class="container margin_60_35">
        <div class="main_title">
            <h2>Oldest Listing</h2>
            <span>Products</span>
            <p>Top viewed Products</p>
        </div>
        <div class="owl-carousel owl-theme products_carousel">
            <!-- featured slider -->
            {% for product in old_products %}
            <div class="item">
                <div class="grid_item">
                    <figure>
                        <span class="ribbon off">  {% percent_discount product.price product.mrp %}   </span>
                        <a href="{% url 'products:product_detail' product.slug %}">
                            {% for image in product.product_images.all|slice:":1" %}
                                <img class="owl-lazy" src="{{image.img.url}}" data-src="{{image.img.url}}" alt="">
                            {% endfor %}
                            
                        </a>
                    </figure>
                    <div class="rating"><i class="icon-star voted"></i><i class="icon-star voted"></i><i class="icon-star voted"></i><i class="icon-star voted"></i><i class="icon-star"></i></div>
                    <a href="{% url 'products:product_detail' product.slug %}">
                        <h3>{{product.name}}</h3>
                    </a>
                    <div class="price_box">
                        <span class="new_price">₹ {{product.price}}</span>
                    </div>
                    <ul>
                        <li><a href="#0" class="tooltip-1" data-bs-toggle="tooltip" data-bs-placement="left" title="Add to favorites"><i class="ti-heart"></i><span>Add to favorites</span></a></li>
                        <li><a href="{% url 'add_to_cart' product.id %}" class="tooltip-1" data-bs-toggle="tooltip" data-bs-placement="left" title="Add to cart"><i class="ti-shopping-cart"></i><span>Add to cart</span></a></li>
                    </ul>
                </div>
                <!-- /grid_item -->
            </div>
            {% endfor %}
        </div>
        <!-- /products_carousel -->
    </div>
    <!-- /container -->
    
    <div class="bg_gray">
        <div class="container margin_30">
            <div id="brands" class="owl-carousel owl-theme">
                {% for brand in t_brands %}
                <!-- brands slider -->
                <div class="item">
                    <a href="#0"><img src="{{brand.imgg.url}}" data-src="{{brand.imgg.url}}" alt="" class="owl-lazy"></a>
                </div><!-- /item -->
                {% endfor %}
                
            </div><!-- /carousel -->
        </div><!-- /container -->
    </div>
    <!-- /bg_gray -->

    <div class="container margin_60_35">
        <div class="main_title">
            <h2>Latest Blogs</h2>
            <span>Blog</span>
            <p>Some of the latest uploaded blogs</p>
        </div>
        <div class="row">
            {% for blog in t_blogs %}
            <!-- latest blogs -->
            <div class="col-lg-6">
                <a class="box_news" href="blog.html">
                    <figure>
                        <img src="{{blog.imgg.url}}" data-src="{{blog.imgg.url}}" alt="" width="400" height="266" class="lazy">
                        <figcaption><strong>{{blog.created_on|date:"j"}}</strong>{{blog.created_on|date:"M"}}</figcaption>
                    </figure>
                    <ul>
                        <li>by Admin</li>
                        <li>{{blog.created_on|date:"M j Y"}}</li>
                    </ul>
                    <h4>{{blog.heading}}</h4>
                    <p>{{blog.preview}}</p>
                </a>
            </div>
            {% endfor %}
            
        </div>
        <!-- /row -->
    </div>
    <!-- /container -->
</main>
<!-- /main -->
{% endblock %}


{% block specific_js %}
<script src="{% static 'js/carousel-home.min.js' %}"></script>
{% endblock %}