blogs/urls.py
from django.urls import path
from . import views

app_name="blogs"

urlpatterns = [
    path('', views.blogs, name='blog_list'),
    path('category/<slug:category_slug>/', views.blogs, name='blog_list_category'),
    path('tag/<slug:tag_slug>/', views.blogs, name='blog_list_tag'),
    path('detail/<slug:blog_slug>/', views.blog_detail, name='blog_detail')
]

my_restart/urls.py
from django.contrib import admin
from django.urls import include,path
from users.views import *
from django.conf import settings 
from django.conf.urls.static import static 


urlpatterns = [
    path('', Home, name='home'),
    path('about/', about, name="about"),
    path('faq/', faq, name="faq"),
    path('contact/', contact, name="contact"),

    path('add_to_cart/<int:product_id>/', add_to_cart, name='add_to_cart'),
    path('cart/', view_cart, name='view_cart'),
    path('update_cart_item/<int:item_id>/<int:new_quantity>/', update_cart_item, name='update_cart_item'),
    path('remove_from_cart/<int:cart_item_id>/', remove_from_cart, name='remove_from_cart'),
    path('checkout/', checkout, name='checkout'),
    path('address/', view_address, name='view_address'),
    path('add-address/', add_address, name='add_address'),
    path('pay/', payment, name='payment'),
    path('checkout-session/', create_checkout_session, name='api_checkout_session'),
    path('payment-details', payment_details, name="view_payment_details"),
    path('orders/', orders_list, name="view_my_orders"),
    path('order-details/<str:order>', order_details, name="view_order_details"),


    
    
    path('account/', Signup),
    path('logout/', user_logout),
    path('users/', include('users.urls')),


    path('blogs/', include('blogs.urls')),
    path('products/', include('products.urls')),
    path('admin/', admin.site.urls),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogs/models.py
from django.db import models
from django.utils.text import slugify
# Create your models here.



class Category(models.Model):
    name = models.CharField(max_length=200)
    created_on=models.DateTimeField(auto_now_add=True)
    updated_on=models.DateTimeField(auto_now=True)
    slug = models.SlugField(unique=True, blank=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

class Tag(models.Model):
    name = models.CharField(max_length=200)
    created_on=models.DateTimeField(auto_now_add=True)
    updated_on=models.DateTimeField(auto_now=True)
    slug = models.SlugField(unique=True, blank=True, default=None )

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Tag, self).save(*args, **kwargs)

    def __str__(self):
        return self.name


class Blog(models.Model):
    category = models.ForeignKey(Category,on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag)
    heading = models.CharField(max_length=200)
    preview = models.CharField(max_length=555)
    detail = models.TextField()
    imgg = models.FileField(upload_to='blog')
    created_on=models.DateTimeField(auto_now_add=True)
    updated_on=models.DateTimeField(auto_now=True)
    slug = models.SlugField(unique=True, blank=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.heading)
        super(Blog, self).save(*args, **kwargs)

    def __str__(self):
        return self.heading    

blogs/views.py
from django.shortcuts import render, get_object_or_404
from .models import *

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


# Create your views here.
def top_blogs(request):
    t_blogs = Blog.objects.all().order_by('-id')[:4]
    return t_blogs


def blogs(request, category_slug=None, tag_slug=None):
    all_blogs = Blog.objects.all()
    
    cat = None
    tag_slug = None
    
    if category_slug:
        cat = get_object_or_404(Category, slug=category_slug)
        all_blogs = all_blogs.filter(category=cat)


    if tag_slug:
        subcat = get_object_or_404(Tag, slug=tag_slug)
        all_blogs = all_blogs.filter(sub_category=subcat)

    
    page = request.GET.get('page', 1)
    paginator = Paginator(all_blogs, 4)
    
    try:
        blogs = paginator.page(page)
    except PageNotAnInteger:
        blogs = paginator.page(1)
    except EmptyPage:
        blogs = paginator.page(paginator.num_pages)

    return render(request, 'blogs/blogs.html', {'all_blogs': blogs})



def blog_detail(request, blog_slug):
    blog_det = get_object_or_404(Blog, slug=blog_slug)
    return render(request, 'blogs/blog-detail.html',{'blog_det':blog_det})

templates/blogs/blog-detail.html
{% extends "includes/base.html" %}

{% load static %}
{% block specific_css %}
	<link href="{% static 'css/blog.css' %}" rel="stylesheet">
{% endblock %}

{% block main_content %}
	<main class="bg_gray">
		<div class="container margin_30">
			<div class="page_header">
				<div class="breadcrumbs">
					<ul>
						<li><a href="#">Home</a></li>
						<li><a href="#">{{blog_det.category}}</a></li>
						<li>{{blog_det.heading}}</li>
					</ul>
				</div>
			</div>
			<!-- /page_header -->
			<div class="row">
				<div class="col-lg-9">
					<div class="singlepost">
						<figure><img alt="" class="img-fluid" src="{{blog_det.imgg.url}}"></figure>
						<h1>{{blog_det.heading}}</h1>
						<div class="postmeta">
							<ul>
								<li><a href="#"><i class="ti-folder"></i> {{blog_det.category}}</a></li>
								<li><i class="ti-calendar"></i> {{blog_det.created_on|date:"M j Y"}}</li>
								<li><a href="#"><i class="ti-user"></i> Admin</a></li>
								<li><a href="#"><i class="ti-comment"></i> (14) Comments</a></li>
							</ul>
						</div>
						<!-- /post meta -->
						<div class="post-content">
							{{blog_det.detail}}
						</div>
						<!-- /post -->
					</div>
					<!-- /single-post -->

					<div id="comments">
						<h5>Comments</h5>
						<ul>
							<li>
								<div class="avatar">
									<a href="#"><img src="img/avatar1.jpg" alt="">
									</a>
								</div>
								<div class="comment_right clearfix">
									<div class="comment_info">
										By <a href="#">Anna Smith</a><span>|</span>25/10/2019<span>|</span><a href="#"><i class="icon-reply"></i></a>
									</div>
									<p>
										Nam cursus tellus quis magna porta adipiscing. Donec et eros leo, non pellentesque arcu. Curabitur vitae mi enim, at vestibulum magna. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed sit amet sem a urna rutrumeger fringilla. Nam vel enim ipsum, et congue ante.
									</p>
								</div>
								<ul class="replied-to">
									<li>
										<div class="avatar">
											<a href="#"><img src="img/avatar2.jpg" alt="">
											</a>
										</div>
										<div class="comment_right clearfix">
											<div class="comment_info">
												By <a href="#">Anna Smith</a><span>|</span>25/10/2019<span>|</span><a href="#"><i class="icon-reply"></i></a>
											</div>
											<p>
												Nam cursus tellus quis magna porta adipiscing. Donec et eros leo, non pellentesque arcu. Curabitur vitae mi enim, at vestibulum magna. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed sit amet sem a urna rutrumeger fringilla. Nam vel enim ipsum, et congue ante.
											</p>
											<p>
												Aenean iaculis sodales dui, non hendrerit lorem rhoncus ut. Pellentesque ullamcorper venenatis elit idaipiscingi Duis tellus neque, tincidunt eget pulvinar sit amet, rutrum nec urna. Suspendisse pretium laoreet elit vel ultricies. Maecenas ullamcorper ultricies rhoncus. Aliquam erat volutpat.
											</p>
										</div>
										<ul class="replied-to">
											<li>
												<div class="avatar">
													<a href="#"><img src="img/avatar2.jpg" alt="">
													</a>
												</div>
												<div class="comment_right clearfix">
													<div class="comment_info">
														By <a href="#">Anna Smith</a><span>|</span>25/10/2019<span>|</span><a href="#"><i class="icon-reply"></i></a>
													</div>
													<p>
														Nam cursus tellus quis magna porta adipiscing. Donec et eros leo, non pellentesque arcu. Curabitur vitae mi enim, at vestibulum magna. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed sit amet sem a urna rutrumeger fringilla. Nam vel enim ipsum, et congue ante.
													</p>
													<p>
														Aenean iaculis sodales dui, non hendrerit lorem rhoncus ut. Pellentesque ullamcorper venenatis elit idaipiscingi Duis tellus neque, tincidunt eget pulvinar sit amet, rutrum nec urna. Suspendisse pretium laoreet elit vel ultricies. Maecenas ullamcorper ultricies rhoncus. Aliquam erat volutpat.
													</p>
												</div>
											</li>
										</ul>
									</li>
								</ul>
							</li>
							<li>
								<div class="avatar">
									<a href="#"><img src="img/avatar3.jpg" alt="">
									</a>
								</div>

								<div class="comment_right clearfix">
									<div class="comment_info">
										By <a href="#">Anna Smith</a><span>|</span>25/10/2019<span>|</span><a href="#"><i class="icon-reply"></i></a>
									</div>
									<p>
										Cursus tellus quis magna porta adipiscin
									</p>
								</div>
							</li>
						</ul>
					</div>

					<hr>

					<h5>Leave a comment</h5>
					<div class="row">
						<div class="col-md-4 col-sm-6">
							<div class="form-group">
								<input type="text" name="name" id="name2" class="form-control" placeholder="Name">
							</div>
						</div>
						<div class="col-md-4 col-sm-6">
							<div class="form-group">
								<input type="text" name="email" id="email2" class="form-control" placeholder="Email">
							</div>
						</div>
						<div class="col-md-4 col-sm-12">
							<div class="form-group">
								<input type="text" name="email" id="website3" class="form-control" placeholder="Website">
							</div>
						</div>
					</div>
					<div class="form-group">
						<textarea class="form-control" name="comments" id="comments2" rows="6" placeholder="Comment"></textarea>
					</div>
					<div class="form-group">
						<button type="submit" id="submit2" class="btn_1 add_bottom_15">Submit</button>
					</div>
					
				</div>
				<!-- /col -->

				<aside class="col-lg-3">
					<div class="widget search_blog">
						<div class="form-group">
							<input type="text" name="search" id="search" class="form-control" placeholder="Search..">
							<button type="submit"><i class="ti-search"></i></button>
						</div>
					</div>
					<!-- /widget -->
					<div class="widget">
						<div class="widget-title">
							<h4>Latest Post</h4>
						</div>
						<ul class="comments-list">
							<li>
								<div class="alignleft">
									<a href="#0"><img src="img/blog-5.jpg" alt=""></a>
								</div>
								<small>Category - 11.08.2016</small>
								<h3><a href="#" title="">Verear qualisque ex minimum...</a></h3>
							</li>
							<li>
								<div class="alignleft">
									<a href="#0"><img src="img/blog-6.jpg" alt=""></a>
								</div>
								<small>Category - 11.08.2016</small>
								<h3><a href="#" title="">Verear qualisque ex minimum...</a></h3>
							</li>
							<li>
								<div class="alignleft">
									<a href="#0"><img src="img/blog-4.jpg" alt=""></a>
								</div>
								<small>Category - 11.08.2016</small>
								<h3><a href="#" title="">Verear qualisque ex minimum...</a></h3>
							</li>
						</ul>
					</div>
					<!-- /widget -->
					<div class="widget">
						<div class="widget-title">
							<h4>Categories</h4>
						</div>
						<ul class="cats">
							<li><a href="#">Food <span>(12)</span></a></li>
							<li><a href="#">Places to visit <span>(21)</span></a></li>
							<li><a href="#">New Places <span>(44)</span></a></li>
							<li><a href="#">Suggestions and guides <span>(31)</span></a></li>
						</ul>
					</div>
					<!-- /widget -->
					<div class="widget">
						<div class="widget-title">
							<h4>Popular Tags</h4>
						</div>
						<div class="tags">
							<a href="#">Food</a>
							<a href="#">Bars</a>
							<a href="#">Cooktails</a>
							<a href="#">Shops</a>
							<a href="#">Best Offers</a>
							<a href="#">Transports</a>
							<a href="#">Restaurants</a>
						</div>
					</div>
					<!-- /widget -->
				</aside>
				<!-- /aside -->
			</div>
			<!-- /row -->
		</div>
		<!-- /container -->
	</main>
	<!--/main-->
	{% endblock %}	

templates/blogs/blogs.html
{% extends "includes/base.html" %}
{% load static %}
{% block specific_css %}
	<link href="{% static 'css/blog.css' %}" rel="stylesheet">
{% endblock %}

{% block main_content %}
	<main class="bg_gray">
		<div class="container margin_30">
			<div class="page_header">
				<div class="breadcrumbs">
					<ul>
						<li><a href="{% url 'home' %}">Home</a></li>
						<li>Blogs </li>
					</ul>
				</div>
				<h1>Ecom Blog &amp; News</h1>
			</div>
			<!-- /page_header -->
			<div class="row">
				<div class="col-lg-9">
					<div class="widget search_blog d-block d-sm-block d-md-block d-lg-none">
						<div class="form-group">
							<input type="text" name="search" id="search" class="form-control" placeholder="Search..">
							<button type="submit"><i class="ti-search"></i></button>
						</div>
					</div>
					<!-- /widget -->
					<div class="row">

						{% for blog in all_blogs %}

						<div class="col-md-6">
							<article class="blog">
								<figure>
									<a href="{% url 'blogs:blog_detail' blog.slug%}"><img src="{{blog.imgg.url}}" alt="">
										<div class="preview"><span>Read more</span></div>
									</a>
								</figure>
								<div class="post_info">
									<small>{{blog.category}} - {{blog.created_on|date:"M j Y"}}</small>
									<h2><a href="{% url 'blogs:blog_detail' blog.slug%}">{{blog.heading}}</a></h2>
									<p>{{blog.preview}}</p>
									<ul>
										<li>
											<div class="thumb"><img src="{% static 'img/avatar.jpg' %}" alt=""></div> Admin
										</li>
										<li><i class="ti-comment"></i>20</li>
									</ul>
								</div>
							</article>
							<!-- /article -->
						</div>
						<!-- /col -->

						{% endfor %}


						
					</div>
					<!-- /row -->

					<div class="pagination__wrapper no_border add_bottom_30">
						<ul class="pagination">
							{% if all_blogs.paginator.num_pages > 1 %}
								{% if all_blogs.has_previous %}
								<li><a href="?page={{ all_blogs.previous_page_number }}" class="prev" title="previous page">&#10094;</a></li>
								{% endif %}
								<li>
									<a href="#" class="active">{{ all_blogs.number }}</a>
								</li>
								{% if all_blogs.has_next %}
								<li><a href="?page={{ all_blogs.next_page_number }}" class="next" title="next page">&#10095;</a></li>
								{% endif %}
							{% endif %}
						</ul>
					</div>
					<!-- /pagination -->

				</div>
				<!-- /col -->

				<aside class="col-lg-3">
					<div class="widget search_blog d-none d-sm-none d-md-none d-lg-block">
						<div class="form-group">
							<input type="text" name="search" id="search_blog" class="form-control" placeholder="Search..">
							<button type="submit"><i class="ti-search"></i></button>
						</div>
					</div>
					<!-- /widget -->
					<div class="widget">
						<div class="widget-title">
							<h4>Categories</h4>
						</div>
						<ul class="cats">
							<li><a href="#">Food <span>(12)</span></a></li>
							<li><a href="#">Places to visit <span>(21)</span></a></li>
							<li><a href="#">New Places <span>(44)</span></a></li>
							<li><a href="#">Suggestions and guides <span>(31)</span></a></li>
						</ul>
					</div>
					<!-- /widget -->
					<div class="widget">
						<div class="widget-title">
							<h4>Popular Tags</h4>
						</div>
						<div class="tags">
							<a href="#">Food</a>
							<a href="#">Bars</a>
							<a href="#">Cooktails</a>
							<a href="#">Shops</a>
							<a href="#">Best Offers</a>
							<a href="#">Transports</a>
							<a href="#">Restaurants</a>
						</div>
					</div>
					<!-- /widget -->
				</aside>
				<!-- /aside -->
			</div>
			<!-- /row -->
		</div>
		<!-- /container -->
	</main>
	<!--/main-->
	{% endblock %}	